<a href="https://colab.research.google.com/github/juli1001/Numpy-Exercises/blob/main/nunpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
import pandas as pd


In [4]:
a1=np.array([1,2,3])

In [5]:
a1

array([1, 2, 3])

In [6]:
a2=np.array([[1,2,3],[4,5,6]])

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.ndim

1

In [11]:
a1.shape

(3,)

In [12]:
a2.ndim

2

In [13]:
a2.shape

(2, 3)

In [14]:
a3.ndim

3

In [15]:
a3.shape

(2, 3, 3)

In [16]:
x=pd.DataFrame(np.random.randint(10,size=(6,4)),columns=["a","b","c","d"])

In [17]:
x

a  b  c  d
0  3  1  3  6
1  9  3  1  4
2  3  4  7  3
3  6  3  3  9
4  4  8  2  6
5  6  5  9  5

In [18]:
x.shape

(6, 4)

In [19]:
x.ndim

2

In [20]:
ones_1=np.ones((10,2))

In [21]:
ones_1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
zeros_1=np.zeros((7,2,3))

In [23]:
zeros_1

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
# range_array=np.arange(0,100,3) is good


In [25]:
x_1=np.random.randint(10,size=(7,2))

In [26]:
x_1

array([[0, 9],
       [8, 0],
       [2, 9],
       [6, 3],
       [1, 7],
       [9, 5],
       [8, 0]])

In [27]:
x_2=np.random.random((3,5))

In [28]:
x_2

array([[0.23518831, 0.61611569, 0.51714141, 0.4258715 , 0.15654737],
       [0.70155786, 0.65921658, 0.77750565, 0.21234857, 0.82617141],
       [0.44517582, 0.83106828, 0.56768558, 0.33179151, 0.1464975 ]])

In [29]:
np.random.seed(42)
x_3=np.random.randint(10, size=(4,6))

In [30]:
x_3
# no change

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [31]:
x_4=np.random.randint(0,11,size=(3,7))
x_4

array([[ 8,  0, 10, 10,  9,  2,  6],
       [ 3,  8,  2,  4,  2,  6,  4],
       [ 8,  6,  1,  3,  8,  1,  9]])

In [32]:
np.unique(x_4)

array([ 0,  1,  2,  3,  4,  6,  8,  9, 10])

In [33]:
x_4[0]

array([ 8,  0, 10, 10,  9,  2,  6])

In [34]:
x_4[0:2]

array([[ 8,  0, 10, 10,  9,  2,  6],
       [ 3,  8,  2,  4,  2,  6,  4]])

In [35]:
x_4[0:2,0:2]

array([[8, 0],
       [3, 8]])

In [36]:
x_5=np.random.randint(0,11,size=(3,5))
x_5

array([[8, 9, 4, 1, 3],
       [6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5]])

In [37]:
# x_5+x_4 no function because the numbers column x_5 is different from the numbers of  of x_4 

In [38]:
x_6=np.random.randint(0,11,size=(3,5))

In [39]:
x_61=np.random.randint(0,11,size=(5,3))

In [40]:
x_5+x_6

array([[13, 18,  7,  6,  4],
       [15,  8, 11,  3, 10],
       [ 7, 15, 10,  5,  6]])

In [41]:
np.dot(x_5,x_61)

array([[164, 182, 117],
       [117, 140,  76],
       [126, 131,  50]])

In [42]:
x_61

array([[ 4,  7,  9],
       [ 8,  8,  0],
       [ 8,  6,  8],
       [ 7,  0,  7],
       [ 7, 10,  2]])

In [43]:
x_61**2

array([[ 16,  49,  81],
       [ 64,  64,   0],
       [ 64,  36,  64],
       [ 49,   0,  49],
       [ 49, 100,   4]])

In [44]:
np.square(x_61)

array([[ 16,  49,  81],
       [ 64,  64,   0],
       [ 64,  36,  64],
       [ 49,   0,  49],
       [ 49, 100,   4]])

In [45]:
np.mean(x_1)

4.785714285714286

In [46]:
np.max(x_61)

10

In [47]:
np.min(x_61)

0

In [48]:
np.std(x_61)

3.0214051182999095

In [49]:
np.var(x_61)

9.12888888888889

In [50]:
x_61.shape

(5, 3)

In [51]:
x_61.reshape(3,5)

array([[ 4,  7,  9,  8,  8],
       [ 0,  8,  6,  8,  7],
       [ 0,  7,  7, 10,  2]])

In [52]:
x_61.T
# change the numbers of columns to the number of rows amd viceversa

array([[ 4,  8,  8,  7,  7],
       [ 7,  8,  6,  0, 10],
       [ 9,  0,  8,  7,  2]])

In [53]:
x_7=np.random.randint(0,11,size=(3,3))
x_7

array([[ 0,  7,  2],
       [ 2,  0, 10],
       [ 4,  9,  6]])

In [54]:
x_8=np.random.randint(0,11,size=(3,2))
x_8

array([[9, 8],
       [6, 8],
       [7, 1]])

In [55]:
np.dot(x_7,x_8)

array([[ 56,  58],
       [ 88,  26],
       [132, 110]])

In [56]:
x_9=np.random.randint(0,11,size=(4,3))

In [57]:
x_10=np.random.randint(0,11,size=(4,3))

In [58]:
x_10.T

array([[ 4,  4,  6,  9],
       [ 2,  9, 10,  9],
       [ 0,  6,  8,  2]])

In [59]:
# np.dot(x_9,x_10) is not possible because the row of 9 have to be the same number of the columns of 10

In [61]:
np.dot(x_9,x_10.T)

array([[ 12,  90, 108,  66],
       [ 36,  76,  98, 103],
       [ 38, 133, 172, 128],
       [  8,  20,  28,  22]])

In [62]:
x_10>x_9

array([[ True, False, False],
       [False,  True,  True],
       [False,  True, False],
       [ True,  True, False]])

In [63]:
x_10>=x_9

array([[ True, False, False],
       [False,  True,  True],
       [False,  True, False],
       [ True,  True,  True]])

In [64]:
x_10>7

array([[False, False, False],
       [False,  True, False],
       [False,  True,  True],
       [ True,  True, False]])

In [65]:
x_10==x_9

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [67]:
np.argsort(x_10)

array([[2, 1, 0],
       [0, 2, 1],
       [0, 2, 1],
       [2, 0, 1]])

In [68]:
np.sort(x_10)

array([[ 0,  2,  4],
       [ 4,  6,  9],
       [ 6,  8, 10],
       [ 2,  9,  9]])

In [69]:
np.argmax(x_10)

7

In [70]:
np.argmin(x_10)

2

In [74]:
np.argmax(x_10,axis=1)

array([0, 1, 1, 0])

In [75]:
np.argmin(x_10,axis=0)

array([0, 0, 0])

In [76]:
np.random.randn(10,4,3)

array([[[ 0.08704707, -0.29900735,  0.09176078],
        [-1.98756891, -0.21967189,  0.35711257],
        [ 1.47789404, -0.51827022, -0.8084936 ],
        [-0.50175704,  0.91540212,  0.32875111]],

       [[-0.5297602 ,  0.51326743,  0.09707755],
        [ 0.96864499, -0.70205309, -0.32766215],
        [-0.39210815, -1.46351495,  0.29612028],
        [ 0.26105527,  0.00511346, -0.23458713]],

       [[-1.41537074, -0.42064532, -0.34271452],
        [-0.80227727, -0.16128571,  0.40405086],
        [ 1.8861859 ,  0.17457781,  0.25755039],
        [-0.07444592, -1.91877122, -0.02651388]],

       [[ 0.06023021,  2.46324211, -0.19236096],
        [ 0.30154734, -0.03471177, -1.16867804],
        [ 1.14282281,  0.75193303,  0.79103195],
        [-0.90938745,  1.40279431, -1.40185106]],

       [[ 0.58685709,  2.19045563, -0.99053633],
        [-0.56629773,  0.09965137, -0.50347565],
        [-1.55066343,  0.06856297, -1.06230371],
        [ 0.47359243, -0.91942423,  1.54993441]],

       [[-

In [77]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])